# If you bump this version, change the version in hitchreqs.in also and
# run ./run.sh make hitchreqs
ARG PLAYWRIGHT_VERSION=1.32.0

FROM mcr.microsoft.com/playwright:v$PLAYWRIGHT_VERSION-focal
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tightvncserver netcat
WORKDIR /root
RUN npm install playwright@$PLAYWRIGHT_VERSION && ./node_modules/.bin/playwright install
COPY playwright-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
