FROM quay.io/podman/stable
# This container contains some magic to make podman-in-podman work well

RUN yum install \
    zlib zlib-devel bzip2 bzip2-devel xz xz-devel \
    openssl openssl-devel sqlite sqlite-devel readline-devel \
    python-devel libuv-devel ncurses-devel libffi-devel \
    python3-virtualenv gcc git curl make vim podman \
    -y && yum clean all

# Ensure podman-in-podman containers/volumes are stored in gen volume
RUN sed -i 's|/var/lib/containers/storage|/gen/containers|g' /etc/containers/storage.conf

RUN mkdir /src
WORKDIR /src
