version: '3.8'

services:
  playwright:
    build:
      dockerfile: tests/Dockerfile-playwright
    image: playwright
    network_mode: host
    environment:
      VNC: ${VNC}
      VNCSCREENSIZE: ${VNCSCREENSIZE}

  app:
    build:
      dockerfile: Dockerfile
    image: app
    network_mode: host
    volumes:
    - /src/app:/app
