version: '3.8'

services:
  playwright:
    network_mode: host
    build:
      dockerfile: tests/Dockerfile-playwright
    image: playwright
    environment:
      VNC: ${VNC}
      VNCSCREENSIZE: ${VNCSCREENSIZE}

  app:
    network_mode: host
    build:
      dockerfile: Dockerfile
    command: runserver
    image: app
    volumes:
    - db-data:/data
    - /src/app:/app
    

volumes:
  db-data:
