version: '3.8'

# !!! WARNING !!!

# ALWAYS ADD network_mode: host to ALL NEW SERVICES
# ALWAYS add docker.io/ to the beginning of any images.
# Otherwise, you can use it like you would any docker-compose.yml.

services:
  playwright:
    network_mode: host
    build:
      dockerfile: tests/Dockerfile-playwright
    image: playwright
    environment:
      VNC: ${VNC}
      VNCSCREENSIZE: ${VNCSCREENSIZE}

  app:
    network_mode: host
    build:
      dockerfile: Dockerfile
    command: runserver
    image: app
    volumes:
    - db-data:/data
    - /src/app:/app
    environment:
    - SQL_ENGINE=django.db.backends.postgresql
    - SQL_DATABASE=hello_django_dev
    - SQL_USER=hello_django
    - SQL_PASSWORD=hello_django
    - SQL_HOST=localhost
    - SQL_PORT=5432

  db:
    # fsync off should NEVER be used in prod but it speeds up tests
    command: -c fsync=off
    network_mode: host
    image: docker.io/postgres:13.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  db-data:
