name: Regression

on:
  workflow_dispatch:

jobs:
  regression:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: build
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          touch ~/.ssh/id_rsa.pub
          echo test | podman secret create pypitoken -
          echo ${{ secrets.GITHUB_TOKEN }} | podman secret create githubtoken -
          ./key.sh make

      - name: regression
        run: ./key.sh docpublish
