name: Example Website Tests Running on Github Actions

on:
  push:
    branches:
    - master
    
    # Only pay attention to the website folder
    paths:
    - examples/website/**

jobs:
  regression:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      #- name: enable arm containers
        #run: |
          #sudo apt-get update
          #sudo apt-get install qemu-system-arm qemu-efi qemu-user-static -y

      # Website Integration Tests
      - name: build environment
        run: |
          cd examples/website
          ./run.sh make

      - name: regression test
        run: |
          cd examples/website
          ./run.sh regression

      - name: save regression test artefacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: regression-test-artefacts
          path: |
            examples/website/hitch/artefacts/**

      #- name: Code Coverage Report
      #  uses: irongut/CodeCoverageSummary@v1.3.0
      #  with:
      #    filename: examples/website/artefacts/coverage.xml
      #    badge: true
      #    fail_below_min: true
      #    format: markdown
      #    hide_branch_rate: false
      #    hide_complexity: false
      #    indicators: true
      #    output: both
      #    thresholds: '60 80'
