name: Regression

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:

jobs:
  regression:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      #- name: ensure qemu installed so arm containers work
        #run: |
          #sudo apt-get update
          #sudo apt-get install qemu-system-arm qemu-efi qemu-user-static -y

      - name: build
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          touch ~/.ssh/id_rsa.pub
          echo test | podman secret create pypitoken -
          ./key.sh make

      - name: regression
        run: ./key.sh regression
